# Generated by Django 5.1.3 on 2024-11-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('teacher', 'Teacher'), ('student', 'Student'), ('admin', 'Admin')], default='user', max_length=50),
        ),
    ]
